export const coursesData = [
  {
    id: 1,
    slug: 'data-analysis',
    title: 'Data Analysis',
    category: 'Data & Analytics',
    price: 300000,
    duration: '3 Months',
    schedule: 'Mon-Wed, 9am-4pm',
    level: 'Beginner to Advanced',
    shortDescription: 'Learn to collect, clean, analyze and visualize data to make informed business decisions.',
    topics: ['Excel', 'SQL', 'Python', 'Power BI', 'Statistics'],
    icon: '📊',
    badge: null
  },
  {
    id: 2,
    slug: 'product-design',
    title: 'Product Design',
    category: 'Design',
    price: 200000,
    duration: '3 Months',
    schedule: 'Mon-Wed, 9am-4pm',
    level: 'Beginner Friendly',
    shortDescription: 'Master user-centered product design from research to prototyping using industry-standard tools.',
    topics: ['Figma', 'User Research', 'Prototyping', 'UI/UX', 'Design Systems'],
    icon: '🎨',
    badge: null
  },
  {
    id: 3,
    slug: 'graphic-design-branding',
    title: 'Graphic Design & Branding',
    category: 'Design',
    price: 200000,
    duration: '3 Months',
    schedule: 'Mon-Wed, 9am-4pm',
    level: 'Beginner Friendly',
    shortDescription: 'Create compelling visual identities and brand experiences with Adobe Creative Suite.',
    topics: ['Photoshop', 'Illustrator', 'InDesign', 'Branding', 'Logo Design'],
    icon: '🎨',
    badge: null
  },
  {
    id: 4,
    slug: 'cybersecurity',
    title: 'Cybersecurity',
    category: 'Other',
    price: 450000,
    duration: '3 Months',
    schedule: 'Mon-Wed, 9am-4pm',
    level: 'Beginner to Advanced',
    shortDescription: 'Protect systems, networks, and data from cyber threats. High-demand career with excellent pay.',
    topics: ['Network Security', 'Ethical Hacking', 'Cryptography', 'Risk Management', 'Penetration Testing'],
    icon: '🔒',
    badge: 'High Demand'
  },
  {
    id: 5,
    slug: 'digital-marketing',
    title: 'Digital Marketing',
    category: 'Marketing',
    price: 250000,
    duration: '3 Months',
    schedule: 'Mon-Wed, 9am-4pm',
    level: 'Beginner Friendly',
    shortDescription: 'Master online marketing strategies including SEO, social media, email, and paid advertising.',
    topics: ['SEO', 'Social Media', 'Google Ads', 'Email Marketing', 'Analytics'],
    icon: '📱',
    badge: null
  },
  {
    id: 6,
    slug: 'cinematography-video-editing',
    title: 'Cinematography & Video Editing',
    category: 'Other',
    price: 250000,
    duration: '3 Months',
    schedule: 'Mon-Wed, 9am-4pm',
    level: 'Beginner to Intermediate',
    shortDescription: 'Master visual storytelling through camera work and post-production with Premiere Pro and After Effects.',
    topics: ['Camera Work', 'Lighting', 'Premiere Pro', 'After Effects', 'Color Grading'],
    icon: '🎬',
    badge: null
  },
  {
    id: 7,
    slug: 'python-programming',
    title: 'Python Programming',
    category: 'Development',
    price: 350000,
    duration: '3 Months',
    schedule: 'Mon-Wed, 9am-4pm',
    level: 'Beginner to Advanced',
    shortDescription: 'Master Python from basics to advanced applications including data analysis, web scraping, and automation.',
    topics: ['Python Basics', 'OOP', 'Data Structures', 'Web Scraping', 'Flask'],
    icon: '🐍',
    badge: null
  },
  {
    id: 8,
    slug: 'full-stack-development',
    title: 'Full Stack Development',
    category: 'Development',
    price: 500000,
    duration: '3 Months',
    schedule: 'Mon-Wed, 9am-4pm',
    level: 'Beginner to Advanced',
    shortDescription: 'Master both frontend and backend development to build complete web applications from scratch.',
    topics: ['React', 'Node.js', 'MongoDB', 'Express', 'Authentication', 'Deployment'],
    icon: '💻',
    badge: 'Most Popular'
  },
  {
    id: 9,
    slug: 'frontend-development',
    title: 'Frontend Development',
    category: 'Development',
    price: 300000,
    duration: '3 Months',
    schedule: 'Mon-Wed, 9am-4pm',
    level: 'Beginner to Intermediate',
    shortDescription: 'Specialize in creating beautiful, interactive user interfaces for web applications.',
    topics: ['HTML/CSS', 'JavaScript', 'React', 'Responsive Design', 'Web Performance'],
    icon: '🎨',
    badge: null
  },
  {
    id: 10,
    slug: 'backend-development',
    title: 'Backend Development',
    category: 'Development',
    price: 300000,
    duration: '3 Months',
    schedule: 'Mon-Wed, 9am-4pm',
    level: 'Intermediate',
    shortDescription: 'Master server-side programming and database management for web applications.',
    topics: ['Node.js', 'Express', 'PostgreSQL', 'MongoDB', 'API Development', 'Authentication'],
    icon: '⚙️',
    badge: null
  },
  {
    id: 11,
    slug: 'product-management',
    title: 'Product Management',
    category: 'Other',
    price: 200000,
    duration: '3 Months',
    schedule: 'Mon-Wed, 9am-4pm',
    level: 'Beginner to Intermediate',
    shortDescription: 'Learn to lead product development from ideation to launch and beyond.',
    topics: ['Product Strategy', 'User Research', 'Roadmapping', 'Agile', 'Analytics'],
    icon: '📋',
    badge: null
  },
  {
    id: 12,
    slug: 'computer-literacy',
    title: 'Computer Literacy',
    category: 'Other',
    price: 100000,
    duration: '3 Months',
    schedule: 'Mon-Wed, 9am-4pm',
    level: 'Absolute Beginner',
    shortDescription: 'Master essential computer skills for the modern workplace including Microsoft Office and digital tools.',
    topics: ['Microsoft Word', 'Excel', 'PowerPoint', 'Email', 'Internet Basics'],
    icon: '💻',
    badge: 'Best for Beginners'
  },
  {
    id: 13,
    slug: 'social-media-management',
    title: 'Social Media Management',
    category: 'Marketing',
    price: 250000,
    duration: '3 Months',
    schedule: 'Mon-Wed, 9am-4pm',
    level: 'Beginner Friendly',
    shortDescription: 'Learn to manage, grow, and monetize social media platforms for businesses and brands.',
    topics: ['Content Creation', 'Instagram', 'Facebook', 'TikTok', 'Analytics', 'Advertising'],
    icon: '📱',
    badge: null
  }
];

export const categories = [
  { label: 'All Courses', value: 'all', count: 13 },
  { label: 'Development', value: 'Development', count: 4 },
  { label: 'Design', value: 'Design', count: 2 },
  { label: 'Marketing', value: 'Marketing', count: 2 },
  { label: 'Data & Analytics', value: 'Data & Analytics', count: 2 },
  { label: 'Other', value: 'Other', count: 3 }
];
